filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
before_commands:
    - 'composer install --prefer-source'
checks:
    php:
        custom_coding_standard:
            git_repository: 'https://github.com/chadicus/coding-standard'
            git_version: '7e6f3114f1a73a78bee8f949afdff241d1ef7ee5'
            ruleset_path: 'Chadicus/ruleset.xml'
tools:
    php_analyzer: true
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_loc:
        excluded_dirs:
            - vendor
            - tests
    php_pdepend: true
    php_sim: true
build_failure_conditions:
    - 'elements.rating(<= B).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 8)'
